# Generated by Django 5.2.7 on 2025-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('create_by', models.BigIntegerField(help_text='创建人ID', null=True, verbose_name='创建人ID')),
                ('update_by', models.BigIntegerField(help_text='修改人ID', null=True, verbose_name='修改人ID')),
                ('create_name', models.CharField(blank=True, help_text='创建人名称', max_length=100, null=True, verbose_name='创建人名称')),
                ('update_name', models.CharField(blank=True, help_text='修改人名称', max_length=100, null=True, verbose_name='修改人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('mobile', models.CharField(blank=True, db_index=True, help_text='电话', max_length=30, null=True, unique=True, verbose_name='电话')),
                ('username', models.CharField(db_index=True, help_text='用户名', max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=60, null=True, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, help_text='头像', max_length=200, null=True, verbose_name='头像')),
                ('gender', models.CharField(blank=True, default='1', help_text='性别', max_length=1, null=True, verbose_name='性别')),
                ('login_ip', models.CharField(blank=True, help_text='最后登录ip', max_length=32, null=True, verbose_name='最后登录ip')),
                ('is_certificated', models.CharField(blank=True, default='0', help_text='是否认证', max_length=1, null=True, verbose_name='是否认证')),
                ('status', models.CharField(blank=True, default='1', help_text='用户状态', max_length=1, null=True, verbose_name='用户状态')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'hte_web_users',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.BigIntegerField(help_text='创建人ID', null=True, verbose_name='创建人ID')),
                ('update_by', models.BigIntegerField(help_text='修改人ID', null=True, verbose_name='修改人ID')),
                ('create_name', models.CharField(blank=True, help_text='创建人名称', max_length=100, null=True, verbose_name='创建人名称')),
                ('update_name', models.CharField(blank=True, help_text='修改人名称', max_length=100, null=True, verbose_name='修改人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='配置名称', max_length=100, verbose_name='配置名称')),
                ('key', models.CharField(help_text='配置键', max_length=100, verbose_name='配置键')),
                ('value', models.CharField(help_text='配置值', max_length=100, verbose_name='配置值')),
                ('type', models.CharField(help_text='系统内置（Y是 N否）', max_length=100, verbose_name='系统内置')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'hte_config',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('create_by', models.BigIntegerField(help_text='创建人ID', null=True, verbose_name='创建人ID')),
                ('update_by', models.BigIntegerField(help_text='修改人ID', null=True, verbose_name='修改人ID')),
                ('create_name', models.CharField(blank=True, help_text='创建人名称', max_length=100, null=True, verbose_name='创建人名称')),
                ('update_name', models.CharField(blank=True, help_text='修改人名称', max_length=100, null=True, verbose_name='修改人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('dict_code', models.BigAutoField(primary_key=True, serialize=False, verbose_name='字典编码')),
                ('dict_sort', models.IntegerField(default=0, verbose_name='字典排序')),
                ('dict_label', models.CharField(default='', max_length=100, verbose_name='字典标签')),
                ('dict_value', models.CharField(default='', max_length=100, verbose_name='字典键值')),
                ('dict_type', models.CharField(default='', max_length=100, verbose_name='字典类型')),
                ('css_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='样式属性（其他样式扩展）')),
                ('list_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='表格回显样式')),
                ('is_default', models.CharField(default='N', max_length=1, verbose_name='是否默认（Y是 N否）')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='状态（0禁用 1启用）')),
            ],
            options={
                'verbose_name': '字典数据表',
                'verbose_name_plural': '字典数据表',
                'db_table': 'hte_dict_data',
                'ordering': ['dict_sort', 'dict_type'],
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.BigIntegerField(help_text='创建人ID', null=True, verbose_name='创建人ID')),
                ('update_by', models.BigIntegerField(help_text='修改人ID', null=True, verbose_name='修改人ID')),
                ('create_name', models.CharField(blank=True, help_text='创建人名称', max_length=100, null=True, verbose_name='创建人名称')),
                ('update_name', models.CharField(blank=True, help_text='修改人名称', max_length=100, null=True, verbose_name='修改人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('name', models.CharField(blank=True, help_text='字典名称', max_length=100, null=True, verbose_name='字典名称')),
                ('type', models.CharField(blank=True, help_text='字典类型', max_length=100, null=True, verbose_name='字典类型')),
                ('status', models.CharField(blank=True, default='1', help_text='状态(0禁用 1启用)', max_length=1, null=True, verbose_name='状态(0禁用 1启用)')),
            ],
            options={
                'verbose_name': '字典类型表',
                'verbose_name_plural': '字典类型表',
                'db_table': 'hte_dict_type',
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.BigIntegerField(help_text='创建人ID', null=True, verbose_name='创建人ID')),
                ('update_by', models.BigIntegerField(help_text='修改人ID', null=True, verbose_name='修改人ID')),
                ('create_name', models.CharField(blank=True, help_text='创建人名称', max_length=100, null=True, verbose_name='创建人名称')),
                ('update_name', models.CharField(blank=True, help_text='修改人名称', max_length=100, null=True, verbose_name='修改人名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('remark', models.CharField(blank=True, help_text='备注', max_length=100, null=True, verbose_name='备注')),
                ('username', models.CharField(blank=True, help_text='登录用户名', max_length=32, null=True, verbose_name='登录用户名')),
                ('ip', models.CharField(blank=True, help_text='登录ip', max_length=32, null=True, verbose_name='登录ip')),
                ('agent', models.CharField(blank=True, help_text='agent信息', max_length=1500, null=True, verbose_name='agent信息')),
                ('browser', models.CharField(blank=True, help_text='浏览器名', max_length=200, null=True, verbose_name='浏览器名')),
                ('os', models.CharField(blank=True, help_text='操作系统', max_length=150, null=True, verbose_name='操作系统')),
                ('login_type', models.IntegerField(choices=[(1, '前台登录'), (2, '后台登录')], default=1, help_text='登录类型', verbose_name='登录类型')),
                ('region', models.CharField(blank=True, help_text='登录地区', max_length=200, null=True, verbose_name='登录地区')),
                ('status', models.CharField(default='1', max_length=1, verbose_name='状态（0失败 1成功）')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'hte_login_log',
                'ordering': ('-create_time',),
            },
        ),
    ]
