from rest_framework import status

# 成功
OK = status.HTTP_200_OK

NO_CONTENT = status.HTTP_204_NO_CONTENT

ACCEPTED = status.HTTP_202_ACCEPTED
# 失败
BAD = status.HTTP_400_BAD_REQUEST
# 无权限
FORBIDDEN = status.HTTP_403_FORBIDDEN
# 未认证
UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
# 创建
CREATED = status.HTTP_201_CREATED
# NOT_FOUND
NOT_FOUND = status.HTTP_404_NOT_FOUND
# INTERNAL_SERVER_ERROR
SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
# TOO_MANY_REQUESTS
TOO_MANY_REQUESTS = status.HTTP_429_TOO_MANY_REQUESTS